---
title: "Analysis of Genetic Data 2: Mapping Genome-Wide Associations"
author: Peter Carbonetto
output:
  beamer_presentation:
    template: beamer.tex
    keep_tex: false
---

```{r knitr-options, echo=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,fig.align = "center",
                      results = "hide", fig.show = "hide", message = FALSE,
		      warning = FALSE)
```

Aims of workshop
================

*List aims here.*

Our research task
=================

*Describe research task here.*

It's your choice
================

Your may choose to...

+ Work through the examples on the RCC cluster.

+ Work through the examples on your laptop.

+ Pair up with your neighbour.

+ Follow what I do on the projector.

*However*,

1. A few of the examples will only run on the RCC cluster.

2. The examples may not produce the exact same result on your laptop.

Software tools we will use today
================================

1. PLINK

2. R

3. R packages ...

4. Basic shell commands such as ...

Outline of workshop
===================

*Add outline here.*

Initial setup (part 1)
======================

+ WiFi

+ Power outlets

+ YubiKeys

+ Pace, questions (e.g., keyboard shortcuts).

Initial setup (part 2)
======================

Download the workshop packet to your laptop.

+ URL: https://github.com/rcc-uchicago/genetic-data-analysis-2

+ Open **slides.pdf** from the **docs** folder. This is useful for
viewing and copying the code from the slides.

+ We may also look at some of the files in the **code** folder. The
code can be viewed with your favourite text editor, or browsed
on GitHub.

Initial setup (part 3)
======================

If you are using the RCC cluster, set up your cluster computing
environment:

1. Connect to midway2.

    + See https://rcc.uchicago.edu/docs/connecting.
    
2. *Add screen and sinteractive commands here.*

Initial setup (part 4)
======================

Download the workshop packet from GitHub.

* URL: https://github.com/rcc-uchicago/genetic-data-analysis-2

If you are using the RCC cluster, you can run these commands to
download the workshop packet to your home directory:

```{bash download-repo, eval=FALSE}
cd ~
git clone https://github.com/rcc-uchicago/
  genetic-data-analysis-2.git
```

What's in the workshop packet
=============================

```
genetic-data-analysis-2
  /bin     # All executables are stored here.
  /code    # Source code used in analyses.
  /data    # "Raw" and processed data.
  /docs    # Additional workshop materials.
  /output  # All results are stored here.
```

Download data
=============

* The data folder in the workshop packet already contains some files
which we will use. However, some files are too large to fit in the git
repository, so we will have to download them separately.

* Describe the steps here and in subsequent slides to download the
large data files (files that are too large to fit in the repository).

The data we will use in our analyses
====================================

In the `data` folder:

*Describe the files included in this folder.*

Explore the data
================

*Add steps here for exploring the data.*